#!/bin/bash
clear
pkg install ncurses-utils -y
pkg install ncurses-bin -y
pkg install wget -y
apt install jq -y -qq --silent
apt install pv -y -qq --silent
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mrelaxe \033[1;37m- \033[1;33m[" | pv -qL 15
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mrelaxe \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "instalador SlowDNS Server" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      instalar"
echo -e "     servidor dnstt para tunelamento de DNS."
echo -e ""
echo -e "         \033[1;33mInstalador pros Noobs \033[1;37m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "baixando dependências" | pv -qL 10
echo ""
fun_att () {
wget https://raw.githubusercontent.com/leitura/slowdns/main/server.key
wget https://raw.githubusercontent.com/leitura/slowdns/main/server.pub
}
fun_bar 'fun_att'
echo -e "configurando firewall" | pv -qL 10
echo ""
fun_ports () {
apt install firewalld -y && sudo firewall-cmd --zone=public --permanent --add-port=80/tcp && sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp && sudo firewall-cmd --zone=public --permanent --add-port=443/tcp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=53/udp && sudo firewall-cmd --zone=public --permanent --add-port=5300/udp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=2222/tcp && sudo firewall-cmd --reload
}
fun_bar 'fun_ports'
sleep 2
clear
PS3='qual você quer ' 
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "qual método de conexão" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
options=("SlowDNS SSH" "SlowDNS SSL")
select opt in "${options[@]}"
do
    case $opt in
        "SlowDNS SSH")
            rm -rf dns-server; wget https://raw.githubusercontent.com/leitura/slowdns/main/ssh/slowdns-install; chmod +x slowdns-install; ./slowdns-install
            break
            ;;
        "SlowDNS SSL")
            rm -rf dns-server; wget https://raw.githubusercontent.com/leitura/slowdns/main/ssl/slowdns-install; chmod +x slowdns-install; ./slowdns-install
            break
            ;;
        *) echo "calma barboleta! $REPLY";;
    esac
done
