#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mrelaxe \033[1;37m- \033[1;33m[" | pv -qL 10
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mrelaxe \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "instalando SlowDNS SSL" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      instalar"
echo -e "     slowdns pro tunelamento de DNS com SSL."
echo -e ""
echo -e "         \033[1;33mInstalador pros Noobs️ \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "atualizando lista de pacotes" | pv -qL 10
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "instalando e atualizando pacotes necessários" | pv -qL 10
install_pkgs () {
apt install screen -y 
apt install cron -y 
apt install iptables -y 
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "baixando binário DNSTT"
download_dnstt () {
cd /root && wget https://github.com/leitura/slowdns/raw/main/dns-server
chmod +x dns-server
}
fun_bar 'download_dnstt'
echo -e "configurando Iptables" | pv -qL 10
ipt_set () {
cd /etc 
rm -rf rc.local
wget https://raw.githubusercontent.com/leitura/slowdns/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m acorda \033[1;33m!!!"
echo ""
echo -ne "\033[1;32m cole seu NS (NameServer)\033[1;37m: " | pv -qL 10; read nameserver
cd /root
touch infons
echo $nameserver >> infons
sleep 1
wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/ssl/startdns 
wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/ssl/restartdns 
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /root/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /root/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
clear
echo -e "ok terminou" | pv -qL 10
finish_ist () {
cd /root
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
FILE=/root/server.key
FILE2=/root/server.pub
if [[ -f FILE ]] && [[ -f FILE2 ]]
then
   echo -e "restaurando Key"
else 
  echo -e "gerando Key"
    ./dns-server -gen-key -privkey-file server.key -pubkey-file server.pub
fi
./startdns
}
fun_bar 'finish_ist'
clear
echo ""
echo -e "\033[1;31m de boa\033[1;33m" | pv -qL 10
echo ""
echo "Seu NS: " && cat /root/infons
echo ""
echo "Sua Key: " && cat /root/server.pub 
echo ""
echo -e "Sua Key tá salva no arquivo /root/server.pub" 
echo ""
echo "Pra reiniciar o SlowDNS, só dar o comando restartdns" 
echo ""
echo -e "Salve os arquivos server.pub e server.key (estão em /root/) num local seguro longe de mim" 
echo "Caso troque de VPS Xing Ling ou precise formatar, apenas coloque os arquivos server.pub e server.key em /root/ e rode esse script de novo" 
echo -e "daí não precisa trocar de Key ao mudar de servidor" 
